name: lookgood_cb007942
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  
  

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  share: ^2.0.1
  google_maps_flutter: ^2.0.6
  dcdg: ^3.1.0
  url_launcher: ^6.0.4
  permission_handler: ^8.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer: ^1.7.0
  async: ^2.7.0
  meta: ^1.4.0
  

flutter:

  uses-material-design: true

  
  assets:
    - assets/icons/

  fonts:
    - family: Trueno
      fonts:
         - asset: assets/fonts/Trueno.ttf
        
  