name: lookgood_cb007942
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_auth:
  cloud_firestore: "^0.16.0+1"

  

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  share: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  
  assets:
    - assets/icons/

  fonts:
    - family: Trueno
      fonts:
         - asset: assets/fonts/Trueno.ttf
        
  